module.exports = function(app) {
    let package = require('../controllers/package.controller')
    let middleware = require('../middlewares/updateHistory.middleware')
    app.route('/package')
        .post(package.create)
        .get(package.list)
    app.route('/package/latest')
        .get(package.latest)
    app.route('/package/popular')
        .get(package.popular)
    app.route('/package/search')
        .get(package.search)
    app.route('/package/:id')
        .get(middleware.updateHistory, package.read)
        .put(package.update)
        .delete(package.delete)
    app.param('id', package.packageById)
}